# Generated by Django 4.1.2 on 2022-11-21 00:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulario', '0001_initial'),
        ('asignacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('respondido', models.DateTimeField(db_column='FECHA_RESPONDIDO', default=datetime.datetime.now, editable=False, verbose_name='Fecha de respuesta')),
                ('latitud', models.CharField(db_column='LATITUD', max_length=25, verbose_name='Latitud')),
                ('longitud', models.CharField(db_column='LONGITUD', max_length=25, verbose_name='Longitud')),
                ('delegacion', models.ForeignKey(db_column='DELEGACION_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Delegación')),
                ('formulario', models.ForeignKey(db_column='FORMULARIO_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='formulario.formulario', verbose_name='Formulario')),
                ('meta', models.ForeignKey(blank=True, db_column='META_ALCANZADA_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='asignacion.metamensual', verbose_name='Meta mensual alcanzada')),
            ],
            options={
                'verbose_name': 'RESPUESTA',
                'verbose_name_plural': 'RESPUESTAS',
                'db_table': 'RESPUESTA',
            },
        ),
        migrations.CreateModel(
            name='DetalleRespuesta',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, db_column='RESPUESTA', max_length=350, verbose_name='Respuesta')),
                ('pregunta', models.ForeignKey(db_column='PREGUNTA_ID', on_delete=django.db.models.deletion.CASCADE, to='formulario.pregunta', verbose_name='Pregunta')),
                ('respuesta', models.ForeignKey(db_column='RESPUESTA_ID', on_delete=django.db.models.deletion.CASCADE, to='respuesta.respuesta', verbose_name='Respuesta de Formulario')),
            ],
            options={
                'verbose_name': 'DETALLE DE RESPUESTA',
                'verbose_name_plural': 'DETALLES DE RESPUESTA',
                'db_table': 'DETALLE_RESPUESTA',
            },
        ),
    ]
