# Generated by Django 4.1.2 on 2023-01-22 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delegacion', '0001_initial'),
        ('area_operativa', '0001_initial'),
        ('eje_prevencion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asignacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPRespuesta',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.CharField(db_column='LATITUD', max_length=25, verbose_name='Latitud')),
                ('longitud', models.CharField(db_column='LONGITUD', max_length=25, verbose_name='Longitud')),
                ('respondido', models.DateField(db_column='FECHA_CREADO', default=django.utils.timezone.now, verbose_name='Fecha respondido')),
                ('lugar_no_priorizado', models.CharField(db_column='NO_PRIORIZADO', max_length=350, verbose_name='Lugar no priorizado')),
                ('lugar_especifico', models.CharField(db_column='LUGAR_ESPECIFICO', max_length=350, verbose_name='Lugar específico')),
                ('observaciones', models.TextField(blank=True, db_column='OBSERVACIONES', max_length=450, verbose_name='Observaciones')),
                ('cantidad', models.PositiveBigIntegerField(db_column='CANTIDAD', verbose_name='Cantidad')),
                ('cantidad_personas', models.PositiveBigIntegerField(db_column='CANTIDAD_PERSONAS', verbose_name='Cantidad de personas')),
                ('ninios', models.PositiveBigIntegerField(db_column='NINIOS', default=0, verbose_name='Niños')),
                ('ninias', models.PositiveBigIntegerField(db_column='NINIAS', default=0, verbose_name='Niñas')),
                ('adolecentes_masculinos', models.PositiveBigIntegerField(db_column='ADOLECENTES_MASCULINOS', default=0, verbose_name='Adolecentes masculinos')),
                ('adolecentes_femeninos', models.PositiveBigIntegerField(db_column='ADOLECENTES_FEMENINOS', default=0, verbose_name='Adolecentes femeninos')),
                ('jovenes_masculinos', models.PositiveBigIntegerField(db_column='JOVENES_MASCULINOS', default=0, verbose_name='Jovenes masculinos')),
                ('jovenes_femeninos', models.PositiveBigIntegerField(db_column='JOVENES_FEMENINOS', default=0, verbose_name='Jovenes femeninos')),
                ('adultos_masculinos', models.PositiveBigIntegerField(db_column='ADULTOS_MASCULINOS', default=0, verbose_name='Adultos masculinos')),
                ('adultos_femeninos', models.PositiveBigIntegerField(db_column='ADULTOS_FEMENINOS', default=0, verbose_name='Adultos femeninos')),
                ('adultos_mayores_masculinos', models.PositiveBigIntegerField(db_column='ADULTOS_MAYORES_MASCULINOS', default=0, verbose_name='Adultos mayores masculinos')),
                ('adultos_mayores_femeninos', models.PositiveBigIntegerField(db_column='ADULTOS_MAYORES_FEMENINOS', default=0, verbose_name='Adultos mayores femeninos')),
                ('xinca', models.PositiveBigIntegerField(db_column='XINCAS', default=0, verbose_name='Xincas')),
                ('garifuna', models.PositiveBigIntegerField(db_column='GARIFUNAS', default=0, verbose_name='Garifunas')),
                ('maya', models.PositiveBigIntegerField(db_column='MAYAS', default=0, verbose_name='Mayas')),
                ('ladino', models.PositiveBigIntegerField(db_column='LADINOS', default=0, verbose_name='Ladinos')),
                ('delegacion', models.ForeignKey(db_column='DELEGACION_ID', on_delete=django.db.models.deletion.CASCADE, to='delegacion.delegacion', verbose_name='Delegación')),
                ('eje', models.ForeignKey(db_column='EJE_TRABAJO', on_delete=django.db.models.deletion.CASCADE, to='eje_prevencion.ejetrabajo', verbose_name='Eje de Trabajo')),
                ('lugar_priorizado', models.ForeignKey(db_column='PRIORIZADO_ID', on_delete=django.db.models.deletion.CASCADE, to='asignacion.lugarpriorizado', verbose_name='Lugar priorizado')),
                ('meta', models.ForeignKey(blank=True, db_column='META_EJE_PREVENCION', null=True, on_delete=django.db.models.deletion.SET_NULL, to='asignacion.metamensualep', verbose_name='Meta mensual eje de prevención')),
                ('plan', models.ForeignKey(db_column='PLAN', on_delete=django.db.models.deletion.CASCADE, to='eje_prevencion.planeje', verbose_name='Plan/Orden')),
                ('producto', models.ForeignKey(db_column='PRODUCTO', on_delete=django.db.models.deletion.CASCADE, to='eje_prevencion.producto', verbose_name='Producto')),
                ('subproducto', models.ForeignKey(db_column='SUBPRODUCTO', on_delete=django.db.models.deletion.CASCADE, to='eje_prevencion.subproducto', verbose_name='Subproducto')),
                ('usuario', models.ForeignKey(db_column='USUARIO_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Respuesta de Eje de Prevención',
                'verbose_name_plural': 'Respuestas de Ejes de Prevención',
                'db_table': 'EJE_PREVENCION_RESPUESTA',
            },
        ),
        migrations.CreateModel(
            name='AORespuesta',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.CharField(db_column='LATITUD', max_length=25, verbose_name='Latitud')),
                ('longitud', models.CharField(db_column='LONGITUD', max_length=25, verbose_name='Longitud')),
                ('respondido', models.DateField(db_column='FECHA_CREADO', default=django.utils.timezone.now, verbose_name='Fecha respondido')),
                ('lugar_no_priorizado', models.CharField(db_column='NO_PRIORIZADO', max_length=350, verbose_name='Lugar no priorizado')),
                ('lugar_apoyo', models.CharField(db_column='LUGAR_APOYO', max_length=350, verbose_name='Lugar de apoyo')),
                ('cantidad', models.PositiveBigIntegerField(db_column='CANTIDAD', verbose_name='Cantidad')),
                ('observaciones', models.TextField(blank=True, db_column='OBSERVACIONES', max_length=450, verbose_name='Observaciones')),
                ('total_identificados', models.PositiveBigIntegerField(db_column='TOTAL_IDENTIFICADOS', default=0, verbose_name='Total de identificados')),
                ('hombres_identificados', models.PositiveBigIntegerField(db_column='HOMBRES_IDENTIFICADOS', default=0, verbose_name='Hombres identificados')),
                ('mujeres_identificadas', models.PositiveBigIntegerField(db_column='MUJERES_IDENTIFICADAS', default=0, verbose_name='Mujeres identificadas')),
                ('autos_identificados', models.PositiveBigIntegerField(db_column='AUTOS_IDENTIFICADOS', default=0, verbose_name='Autos identificados')),
                ('motos_identificadas', models.PositiveBigIntegerField(db_column='MOTOS_IDENTIFICADAS', default=0, verbose_name='Motos identificadas')),
                ('armas_identificadas', models.PositiveBigIntegerField(db_column='ARMAS_IDENTIFICADAS', default=0, verbose_name='Armas identificadas')),
                ('total_consignados', models.PositiveBigIntegerField(db_column='TOTA_CONSIGNADOS', default=0, verbose_name='Total consignados')),
                ('hombres_consignados', models.PositiveBigIntegerField(db_column='HOMBRES_CONSIGNADOS', default=0, verbose_name='Hombres consignados')),
                ('mujeres_consignadas', models.PositiveBigIntegerField(db_column='MUJERES_CONSIGNADAS', default=0, verbose_name='Mujeres consignadas')),
                ('autos_consignados', models.PositiveBigIntegerField(db_column='AUTOS_CONSIGNADOS', default=0, verbose_name='Autos consignados')),
                ('motos_consignadas', models.PositiveBigIntegerField(db_column='MOTOS_CONSIGNADAS', default=0, verbose_name='Motos consignadas')),
                ('armas_consignadas', models.PositiveBigIntegerField(db_column='ARRMAS_CONSIGNADAS', default=0, verbose_name='Armas consignadas')),
                ('total_conducidos', models.PositiveBigIntegerField(db_column='TOTAL_CONDUCIDOS', default=0, verbose_name='Total conducidos')),
                ('hombres_conducidos', models.PositiveBigIntegerField(db_column='HOMBRES_CONDUCIDOS', default=0, verbose_name='Hombres conducidos')),
                ('mujeres_conducidas', models.PositiveBigIntegerField(db_column='MUJERES_CONDUCIDAS', default=0, verbose_name='Mujeres conducidas')),
                ('total_solventes', models.PositiveBigIntegerField(db_column='TOTAL_SOLVENTES', default=0, verbose_name='Total solventes')),
                ('hombres_solventes', models.PositiveBigIntegerField(db_column='HOMBRES_SOLVENTES', default=0, verbose_name='Hombres solventes')),
                ('mujeres_solventes', models.PositiveBigIntegerField(db_column='MUJERES_SOLVENTES', default=0, verbose_name='Mujeres solventes')),
                ('autos_solventes', models.PositiveBigIntegerField(db_column='AUTOS_SOLVENTES', default=0, verbose_name='Autos solventes')),
                ('motos_solventes', models.PositiveBigIntegerField(db_column='MOTOS_SOLVENTES', default=0, verbose_name='Motos solventes')),
                ('armas_solventes', models.PositiveBigIntegerField(db_column='ARMAS_SOLVENTES', default=0, verbose_name='Armas solventes')),
                ('total_recuperados', models.PositiveBigIntegerField(db_column='TOTAL_RECUPERADOS', default=0, verbose_name='Total recuperados')),
                ('autos_recuperados', models.PositiveBigIntegerField(db_column='AUTOS_RECUPERADOS', default=0, verbose_name='Autos recuperados')),
                ('motos_recuperados', models.PositiveBigIntegerField(db_column='MOTOS_RECUPERADAS', default=0, verbose_name='Motos recuperadas')),
                ('armas_recuperados', models.PositiveBigIntegerField(db_column='ARMAS_RECUPERADAS', default=0, verbose_name='Armas recuperadas')),
                ('hombres_recuperados', models.PositiveBigIntegerField(db_column='HOMBRES_RECUPERADOS', default=0, verbose_name='Hombres recuperados')),
                ('mujeres_recuperadas', models.PositiveBigIntegerField(db_column='MUJERES_RECUPERADAS', default=0, verbose_name='Mujeres recuperadas')),
                ('menores_recuperados', models.PositiveBigIntegerField(db_column='MENORES_RECUPERADOS', default=0, verbose_name='Menores recuperados')),
                ('delegacion', models.ForeignKey(db_column='DELEGACION_ID', on_delete=django.db.models.deletion.CASCADE, to='delegacion.delegacion', verbose_name='Delegación')),
                ('lugar_priorizado', models.ForeignKey(db_column='PRIORIZADO_ID', on_delete=django.db.models.deletion.CASCADE, to='asignacion.lugarpriorizado', verbose_name='Lugar priorizado')),
                ('operativo', models.ForeignKey(db_column='TIPO_OPERATIVO', on_delete=django.db.models.deletion.CASCADE, to='area_operativa.tipooperativo', verbose_name='Tipo de Operativo')),
                ('plan', models.ForeignKey(db_column='PLAN', on_delete=django.db.models.deletion.CASCADE, to='area_operativa.planarea', verbose_name='Plan/Orden')),
                ('usuario', models.ForeignKey(db_column='USUARIO_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Respuesta de Área Operativa',
                'verbose_name_plural': 'Respuestas de Área Operativa',
                'db_table': 'AREA_OPERATIVA_RESPUESTA',
            },
        ),
    ]
