# Generated by Django 4.1.2 on 2022-11-11 06:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
        ('respuesta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='formulario',
            field=models.ForeignKey(db_column='FORMULARIO_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='formulario.formulario', verbose_name='Formulario'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='respondido',
            field=models.DateTimeField(db_column='FECHA_RESPONDIDO', default=datetime.datetime.now, editable=False, verbose_name='Fecha de respuesta'),
        ),
    ]
