CREATE DATABASE SGPD_DB;

USE SGPD_DB;

/*-----------------------------------------------------------CREACION TABLAS--------------------------------------------------------*/
CREATE TABLE IF NOT EXISTS TIPO_OPERATIVO
(
ID INT NOT NULL, /*PK*/
TIPO VARCHAR (350) NOT NULL,/*SUELEN COLOCAR MUCHO TEXTO*/
OPERACION_ID INT /*FK*/
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS OPERACION
(
ID INT NOT NULL, /*PK*/
NOMBRE VARCHAR (30)/*SOLO SELECCION*/
)ENGINE=InnoDB; 

CREATE TABLE IF NOT EXISTS EJE_TRABAJO
(
ID INT NOT NULL, /*PK*/
NOMBRE VARCHAR (350) NOT NULL,/*SUELEN COLOCAR MUCHO TEXTO*/
OPERACION_ID INT /*FK*/
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PRODUCTO
(
ID INT NOT NULL, /*PK*/
NOMBRE VARCHAR (80) NOT NULL,/*COLCAN RELATIVAMENTE MUCHO TEXTO*/
OPERACIONE_ID INT /*FK*/
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PLAN
(
ID INT NOT NULL, /*PK*/
NOMBRE VARCHAR (350),/*SUELEN COLOCAR MUCHO TEXTO*/
OPERACION_ID INT /*FK*/
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS FORMULARIO
(
ID INT NOT NULL, /*PK*/
TITULO VARCHAR (25) NOT NULL,
PORTADA VARCHAR (7),/*HeXadecimal para colores*/
DESCRIPCION VARCHAR (255),/**/
PLAN_ID INT /*FK*/
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SUBPRODUCTO
(
ID INT NOT NULL, /*PK*/
NOMBRE VARCHAR (350),/*Suelen colocar mucho texto*/
PRODUCTO_ID INT /*FK*/
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS SECCION
(
ID INT NOT NULL, /*PK*/
TITULO VARCHAR (25) NOT NULL, /*  */
FORMULARIO_ID INT /*FK*/
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PREGUNTA
(
ID INT NOT NULL, /*PK*/
ENUNCIADO VARCHAR (350),
FORMULARIO_ID INT, /*FK*/
TIPOC_ID INT, /*FK*/
SECCION_ID INT/*FK*/
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS TIPO_CAMPO
(
ID INT NOT NULL, /*PK*/
NOMBRE VARCHAR (15)/*ESTO ES UTILIZADO PARA DEFINIR EL TIPO DE DATO QUE SE USARA, NUMERICO, TEXTO CORTO, TEXTO LARGO, FECHA, HORA, ETC.)*/
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS DETALLE_RESPUESTA
(
ID INT NOT NULL, /*PK*/
RESPUESTA VARCHAR (350),
PREGUNTA_ID INT, /*FK*/
RESPUESTA_ID INT /*FK*/
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS DEPARTAMENTO
(
ID INT NOT NULL, /*PK*/
NOMBRE VARCHAR (30)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS MUNICIPIO
(
ID INT NOT NULL, /*PK*/
NOMBRE VARCHAR (40),/*EXISTEN MUNICIPIOS CON NOMBRES LARGOS*/
DEPARTAMENTO_ID INT /*FK*/
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS LUGAR
(
ID INT NOT NULL, /*PK*/
DIRECCION VARCHAR (150),
ESTADO_ID INT, /*FK*/
MUNICIPIO_ID INT, /*FK*/
DELEGACION_ID INT /*FK*/
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ESTADO
(
ID INT NOT NULL, /*PK*/
NOMBRE VARCHAR (25)
)ENGINE=InnoDB;

/* CREATE TABLE IF NOT EXISTS DELEGACION
(
ID INT NOT NULL, -- PK
NOMBRE VARCHAR (35), -- GENERICO
USUARIO VARCHAR (25) -- FK DONDE ESTA LA LA RELACION DE USAURIO?
)ENGINE=InnoDB;
*/
CREATE TABLE IF NOT EXISTS RESPUESTA
(
ID INT NOT NULL, /*PK*/
LATITUD VARCHAR (12),/*SOLO ACEPTA 12 CARACTERES*/
LONGITUD VARCHAR (13),/*SOLO ACEPTA 13 CARACTERES*/
DELEGACION_ID INT, /*FK*/
FORMULARIO_ID INT /*FK*/
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS IMG /*ESTO ES TABLA IMAGEN*/
(
ID INT NOT NULL, /*PK*/
NOMBRE VARCHAR (215),/*NOMBRE DE LA IMAGEN/ WINDWOS 11 SOLO RESISTE 216 QUACKS  */
SRC VARCHAR (220),/*NOMBRE + 5 CARATERES, EJEMPLO: .PNG. .JPGE. .ICO*/
PGSECCION_ID INT /*FK*/
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS PAGINA_SECCION
(
ID INT NOT NULL,
TITULO VARCHAR (25) NOT NULL,/*ES EL TITULO DEL APARTADO DE CADA SECCION*/
INFORMACION VARCHAR (350)/*AQUI SE GUARDARA URLS DE */
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS RED_SOCIAL
(
ID INT NOT NULL, /*PK*/
NOMBRE VARCHAR (15),/*NOMBRE DE LA RED SOCIAL*/
HABILITADO TINYINT(1), /*BOOLEAN*/
SRC varchar (350)/*URL DE LA RED SOCIAL*/
)ENGINE=Innodb;

CREATE TABLE IF NOT EXISTS ASIGNACION
(
LUGAR_ID INT NOT NULL, /*LUGAR AL QUE SE LE ASIGNARA */
DELEGACION_ID INT NOT NULL /*FK*/
)ENGINE=Innodb;

CREATE TABLE IF NOT EXISTS NOTIFICACION
(
ID INT, /*PK*/
MOTIVO VARCHAR (25),/*MENSAJE TITULO DE LA NOTIFICACION*/
MENSAJE VARCHAR (350),/*MENSAJE QUE SE ENVIARA COMO NOTIFICACION*/
DESTINARIO VARCHAR (150),/*ES USUARIO*/
EMISOR VARCHAR (150), /*ES USUARIO*/
LEIDO TINYINT(1),/*BOOLEAN*/
)ENGINE=Innodb;/*ES PARA IDENTIFICAR EL TIPO DE MOTOR DE TABLA*/

/*
CREADO_FECHA DATE,
CREADO_USUARIO VARCHAR(25),
MODIFICADO_FECHA DATE,
MODIFICADO_USUARIO VARCHAR(25),
*/

CREATE TABLE IF NOT EXISTS DESTINATARIO
(
ID INT NOT NULL, /*PK*/
USUARIO VARCHAR (25),
NOTIFICACION_ID INT/*FK*/
)ENGINE=Innodb;

/*-----------------------------------------------------------CREACION DE LLAVES PRIMARIAS (LLAVES PRIMARIA COMPUIESTA)-------------------------------------------------------------------------------------------------------------*/
/*lOS CONSTRAINT TIENEN QUE TENER PK_ + NOMBRE_ TABLA*/

ALTER TABLE TIPO_OPERATIVO
ADD CONSTRAINT PK_TIPO_OPERATIVO PRIMARY KEY (ID);/*CREACION DE PK T_OPERATIVO*/

ALTER TABLE OPERACION
ADD CONSTRAINT PK_OPERACION PRIMARY KEY (ID);/*CREACION DE PK PK_OPERACION*/

ALTER TABLE PLAN
ADD CONSTRAINT PK_PLAN PRIMARY KEY (ID);/*CREACION DE PK_PLAN*/

ALTER TABLE FORMULARIO
ADD CONSTRAINT PK_FORMULARIO PRIMARY KEY (ID);/*CREACION PK FORMULARIO*/

ALTER TABLE SECCION
ADD CONSTRAINT PK_SECCION PRIMARY KEY FORMULARIO (ID);/*CREACION DE PK SECCION*/

ALTER TABLE HISTORIAL 
ADD CONSTRAINT PK_HISTORIAL PRIMARY KEY (NUM,FECHA);/*CREACION DE PK COMPUIESTA POR NUM Y FECHA */

ALTER TABLE DEPARTAMENTO
ADD CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (ID);/*CREACION DE PK DEPARTAMENTO*/

ALTER TABLE SUBPRODUCTO
ADD CONSTRAINT PK_SUBPRODUCTO PRIMARY KEY (ID);/*CREACION DE PK SUBPRODUCTO*/

ALTER TABLE MUNICIPIO
ADD CONSTRAINT PK_MUNICIPIO PRIMARY KEY (ID);/*CREACION DE PK MUNICIPIO*/

ALTER TABLE PRODUCTO
ADD CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID);/* CREACION DE PK PRODUCTO*/

ALTER TABLE LUGAR
ADD CONSTRAINT PK_LUGAR PRIMARY KEY (ID);/*CREACION DE PK LUGAR */

ALTER TABLE ESTADO
ADD CONSTRAINT PK_ESTADO PRIMARY KEY (ID);/* CREACION DE PK ESTADO*/

ALTER TABLE ASIGNACION
ADD CONSTRAINT PK_ASIGNACION PRIMARY KEY (DELEGACION_ID,LUGAR_ID);/* CREACION DE PK ASIGNACION*/

ALTER TABLE NOTIFICACION
ADD CONSTRAINT PK_NOTIFICACION PRIMARY KEY (ID);/* CREACION DE PK NOTIFICACION*/

/*ALTER TABLE NOTIFICACION
ADD FK_NOTIFICACION_ FOREIGN KEY (EMISOR) REFERENCES XD (ID);*/ /*AUN SE TIENE QUE AGREGAR REFERENCES*/
ALTER TABLE DELEGACION
ADD CONSTRAINT PK_DELEGACION PRIMARY KEY (ID);/* CREACION DE PK DELEGACION*/
/*ALTER TABLE DELEGACION
ADD PK_DELEGACION FOREIGN KEY (USUARIO) REFERENCES xd (ID);*/ /*AUN SE TIENE QUE AGREGAR REFERENCES*/

ALTER TABLE DESTINATARIO
ADD CONSTRAINT PK_DESTINATARIO PRIMARY KEY (ID);/* CREACIUON DE PK DESTINARIO*/

ALTER TABLE RESPUESTA
ADD CONSTRAINT PK_RESPUESTA PRIMARY KEY (ID);/*CREACION DE PK RESPUESTA*/

ALTER TABLE RED_SOCIAL
ADD CONSTRAINT PK_RED_SOCIAL PRIMARY KEY (ID);/*CREACION DE PK RESD_SOCIAL*/

ALTER TABLE PREGUNTA
ADD CONSTRAINT PK_PREGUNTA  PRIMARY KEY (ID);/*CREACION DE PK PREGUNTA*/

ALTER TABLE TIPO_CAMPO
ADD CONSTRAINT PK_TIPO_CAMBIO PRIMARY KEY (ID);/*CREACION DE PK TIPO_CAMBIO*/

ALTER TABLE DETALLE_RESPUESTA
ADD CONSTRAINT PK_DETALLE_RESPUESTA PRIMARY KEY (ID);/*CREACION DE PK DETALLE_RESPUESTA*/

ALTER TABLE PAGINA_SECCION
ADD CONSTRAINT PK_PAGINA_SECCION PRIMARY KEY (ID);/*CREACION DE PK PREGUNTA*/

ALTER TABLE IMG
ADD CONSTRAINT PK_IMG PRIMARY KEY (ID);/*CREACION DE PK IMG (IMAGEN)*/

/*-------------------------------------------------CREACION DE LLAVES FORANEAS------------------------------------------------------------------------------------------------------------------------------------------------------*/
ALTER TABLE TIPO_OPERATIVO
ADD CONSTRAINT FK_TIPO_OPERATIVO_OPERACION
FOREIGN KEY (OPERACION_ID) REFERENCES OPERACION (ID)
ON DELETE SET NULL;/*CREACION DE FK TIPO_OPERATIVO*/

ALTER TABLE PLAN
ADD CONSTRAINT FK_PLAN_OPERACION
FOREIGN KEY (OPERACION_ID) REFERENCES OPERACION (ID)
ON DELETE SET NULL;/*CREACION DE FK PLAN*/

ALTER TABLE FORMULARIO
ADD CONSTRAINT FK_FORMULARIO_PLAN 
FOREIGN KEY (PLAN_ID) REFERENCES PLAN (ID)
ON DELETE SET NULL;/*CREACION DE FK FORMULARIO*/

ALTER TABLE SECCION
ADD CONSTRAINT FK_SECCION_FORMULARIO
FOREIGN KEY (FORMULARIO_ID) REFERENCES FORMULARIO (ID)
ON DELETE SET NULL;/*CREACION DE FK SECCION*/

ALTER TABLE SUBPRODUCTO
ADD CONSTRAINT FK_SUBPRODUCTO_PRODUCTO
FOREIGN KEY  (PRODUCTO_ID) REFERENCES PRODUCTO (ID)
ON DELETE SET NULL;/*CREACION DE FK SUBPRODUCTO*/

ALTER TABLE MUNICIPIO
ADD CONSTRAINT FK_MUNICIPIO_DEPARTAMENTO
FOREIGN KEY (DEPARTAMENTO_ID) REFERENCES DEPARTAMENTO (ID)
ON DELETE SET NULL;/*CREACION DE FK MUNICIPIO*/

ALTER TABLE ASIGNACION
ADD CONSTRAINT FK_ASIGNACION_DELEGACION
FOREIGN KEY (DELEGACION_ID) REFERENCES DELEGACION  (ID)
ON DELETE CASCADE; /* CREACION DE FK ASIGNACION*/

ALTER TABLE ASIGNACION
ADD CONSTRAINT FK_ASIGNACION_LUGAR
FOREIGN KEY (LUGAR_ID) REFERENCES LUGAR  (ID)
ON DELETE CASCADE; /* CREACION DE FK ASIGNACION*/

ALTER TABLE PREGUNTA
ADD CONSTRAINT FK_PREGUNTA_FORMULARIO
FOREIGN KEY (FORMULARIO_ID) REFERENCES FORMULARIO (ID)
ON DELETE SET NULL; /*CREACION DE FK PREGUNTA*/

ALTER TABLE PREGUNTA
ADD CONSTRAINT FK_PREGUNTA_TIPO_CAMPO
FOREIGN KEY (TIPOC_ID) REFERENCES TIPO_CAMPO (ID);/*CREACION DE FK PREGUNTA*/

ALTER TABLE PREGUNTA
ADD CONSTRAINT FK_PREGUNTA_SECCION
FOREIGN KEY (SECCION_ID) REFERENCES SECCION (ID)
ON DELETE SET NULL ;/*CREACION DE FK PREGUNTA*/

ALTER TABLE PRODUCTO
ADD CONSTRAINT FK_PRODUCTO_OPERACION
FOREIGN KEY (OPERACION_ID) REFERENCES OPERACION (ID)
ON DELETE SET NULL;/*CREACION DE FK PRODUCTO*/
/*---------------------------------------------------*/
ALTER TABLE DESTINATARIO
ADD CONSTRAINT FK_DESTINATARIO_NOTIFICACION
FOREIGN KEY (NOTIFICACION_ID) REFERENCES NOTIFICACION (ID)
ON DELETE SET NULL;/* CREACION DE FK DESTINARIO*/
/*---------------------------------------------------*/
ALTER TABLE DETALLE_RESPUESTA
ADD CONSTRAINT FK_DETALLE_RESPUESTA_PREGUNTA 
FOREIGN KEY (PREGUNTA_ID) REFERENCES PREGUNTA (ID)
ON DELETE SET NULL; /*CREACION DE FK DETALLE_RESPUESTA*/

ALTER TABLE DETALLE_RESPUESTA
ADD CONSTRAINT FK_DETALLE_RESPUESTA 
FOREIGN KEY (RESPUESTA_ID) REFERENCES RESPUESTA (ID)
ON DELETE SET NULL;/*CREACION DE FK DETALLE_RESPUESTA*/

ALTER TABLE IMG
ADD CONSTRAINT FK_IMG_PAGINA_SECCION
FOREIGN KEY (PGSECCION_ID) REFERENCES PAGINA_SECCION(ID)
ON DELETE SET NULL;/*CREACION DE FK IMG*/

ALTER TABLE EJE_TRABAJO
ADD CONSTRAINT FK_EJE_TRABAJO_OPERACION
FOREIGN KEY (OPERACION_ID) REFERENCES OPERACION (ID)
ON DELETE SET NULL;/*CREACION DE FK EJE_TRABAJO*/

ALTER TABLE RESPUESTA
ADD CONSTRAINT FK_RESPUESTA_DELEGACION
FOREIGN KEY (DELEGACION_ID) REFERENCES DELEGACION (ID)
ON DELETE SET NULL;/*CREEACION DE FK RESPUESTA-------*/

ALTER TABLE RESPUESTA
ADD CONSTRAINT FK_RESPUESTA_FORMULARIO
FOREIGN KEY (FORMULARIO_ID) REFERENCES FORMULARIO (ID)
ON DELETE SET NULL;/*CREACION DE FK RESPUESTA*/

ALTER TABLE LUGAR
ADD CONSTRAINT FK_LUGAR_ESTADO
FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO (ID)
ON DELETE SET NULL; /* CREACION DE FK LUGAR*/

ALTER TABLE LUGAR
ADD CONSTRAINT FK_LUGAR_MUNICIPIO 
FOREIGN KEY (MUNICIPIO_ID) REFERENCES MUNICIPIO (ID)
ON DELETE SET NULL;/* CREACION DE FK LUGAR*/
/*
ALTER TABLE LUGAR
ADD CONSTRAINT FK_LUGAR_DELEGACION 
FOREIGN KEY (DELEGACION_ID) REFERENCES DELEGACION (ID)
ON DELETE SET NULL;/* CREACION DE FK LUGAR --ESTO NO
*/