# Generated by Django 4.1.2 on 2022-11-23 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=350, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Operación',
                'verbose_name_plural': 'Operaciones',
                'db_table': 'OPERACION',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=350, verbose_name='Nombre')),
                ('operacion', models.ForeignKey(db_column='Operaciones', on_delete=django.db.models.deletion.CASCADE, to='operacion.operacion', verbose_name='Operación')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'PRODUCTO',
            },
        ),
        migrations.CreateModel(
            name='TipoOperativo',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=350, verbose_name='Nombre')),
                ('operacion', models.ForeignKey(db_column='Operaciones', on_delete=django.db.models.deletion.CASCADE, to='operacion.operacion', verbose_name='Operación')),
            ],
            options={
                'verbose_name': 'Tipo de operativo',
                'verbose_name_plural': 'Tipos de operativo',
                'db_table': 'TIPO_OPERATIVO',
            },
        ),
        migrations.CreateModel(
            name='Subproducto',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=350, verbose_name='Nombre')),
                ('producto', models.ForeignKey(db_column='PRODUCTO_ID', on_delete=django.db.models.deletion.CASCADE, to='operacion.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Subproducto',
                'verbose_name_plural': 'Subproductos',
                'db_table': 'SUBPRODUCTO',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=350, verbose_name='Nombre')),
                ('operacion', models.ForeignKey(db_column='Operaciones', on_delete=django.db.models.deletion.CASCADE, to='operacion.operacion', verbose_name='Operación')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'db_table': 'PLAN',
            },
        ),
        migrations.CreateModel(
            name='EjeTrabajo',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=350, verbose_name='Nombre')),
                ('operacion', models.ForeignKey(db_column='Operaciones', on_delete=django.db.models.deletion.CASCADE, to='operacion.operacion', verbose_name='Operación')),
            ],
            options={
                'verbose_name': 'Eje de trabajo',
                'verbose_name_plural': 'Ejes de trabajo',
                'db_table': 'EJE_TRABAJO',
            },
        ),
    ]
