# Generated by Django 4.1.2 on 2022-11-21 00:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operacion', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_column='TITULO', max_length=40, verbose_name='Título')),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=255, verbose_name='Descripción')),
                ('creado', models.DateTimeField(db_column='FECHA_CREADO', default=datetime.datetime.now, editable=False, verbose_name='Fecha de Creación')),
                ('operacion', models.ForeignKey(db_column='OPERACION_ID', on_delete=django.db.models.deletion.CASCADE, to='operacion.operacion', verbose_name='Operación')),
            ],
            options={
                'verbose_name': 'FORMULARIO',
                'verbose_name_plural': 'FORMULARIOS',
                'db_table': 'FORMULARIO',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(db_column='ENUNCIADO', max_length=350, verbose_name='Enunciado de Pregunta')),
                ('campo', models.CharField(choices=[('txc', 'Texto corto'), ('txl', 'Texto largo'), ('num', 'Número'), ('rad', 'Radial'), ('cas', 'Casillas'), ('list', 'Lista')], db_column='CAMPO', max_length=15, verbose_name='Tipo de campo')),
                ('formulario', models.ForeignKey(db_column='FORMULARIO_ID', on_delete=django.db.models.deletion.CASCADE, to='formulario.formulario', verbose_name='Formulario')),
            ],
            options={
                'verbose_name': 'PREGUNTA',
                'verbose_name_plural': 'PREGUNTAS',
                'db_table': 'PREGUNTA',
            },
        ),
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(choices=[('me', 'Menor que'), ('ma', 'Mayor que'), ('mei', 'Menor o igual que'), ('mai', 'Mayor o igual que'), ('i', 'Igual que')], db_column='CONDICION', max_length=30, verbose_name='Condición')),
                ('numero_a_validar', models.PositiveBigIntegerField(db_column='NUMERO_A_VALIDAR', verbose_name='Número a validar')),
                ('pregunta', models.ForeignKey(db_column='PREGUNTA_ID', on_delete=django.db.models.deletion.CASCADE, to='formulario.pregunta', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'VALIDACION',
                'verbose_name_plural': 'VALIDACIONES',
            },
        ),
        migrations.CreateModel(
            name='SeccionFormulario',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_column='TITULO', max_length=40, verbose_name='Título')),
                ('formulario', models.ForeignKey(db_column='FORMULARIO_ID', on_delete=django.db.models.deletion.CASCADE, to='formulario.formulario', verbose_name='Formulario')),
            ],
            options={
                'verbose_name': 'SECCION DE FORMULARIO',
                'verbose_name_plural': 'SECCIONES DE FORMULARIO',
                'db_table': 'SECCION_FORMULARIO',
            },
        ),
        migrations.CreateModel(
            name='PreguntaAuxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(choices=[('plan', 'PLAN'), ('eje', 'EJE DE TRABAJO'), ('producto', 'PRODUCTO'), ('toperativo', 'TIPO DE OPERATIVO')], db_column='PREGUNTA', max_length=20, unique=True, verbose_name='Pregunta')),
                ('formulario', models.ForeignKey(db_column='FORMULARIO_ID', on_delete=django.db.models.deletion.CASCADE, to='formulario.formulario', verbose_name='Formulario')),
            ],
            options={
                'verbose_name': 'PREGUNTA AUXILIAR',
                'verbose_name_plural': 'PREGUNTAS AUXILIARES',
                'db_table': 'PREGUNTA_AUXILIAR',
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='seccion',
            field=models.ForeignKey(blank=True, db_column='SECCION_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='formulario.seccionformulario', verbose_name='Sección'),
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=250, verbose_name='Nombre')),
                ('pregunta', models.ForeignKey(db_column='PREGUNTA_ID', on_delete=django.db.models.deletion.CASCADE, to='formulario.pregunta', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'OPCION',
                'verbose_name_plural': 'OPCIONES',
                'db_table': 'OPCION',
            },
        ),
    ]
