# Generated by Django 4.1.2 on 2022-10-19 19:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_column='TITULO', max_length=40, verbose_name='Título')),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=255, verbose_name='Descripción')),
                ('creado', models.DateTimeField(db_column='FECHA_CREADO', default=datetime.datetime.now, editable=False, verbose_name='Fecha de Creación')),
                ('plan', models.ForeignKey(db_column='PLAN_ID', on_delete=django.db.models.deletion.CASCADE, to='operacion.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'FORMULARIO',
                'verbose_name_plural': 'FORMULARIOS',
                'db_table': 'FORMULARIO',
            },
        ),
        migrations.CreateModel(
            name='TipoCampo',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=20, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'TIPO DE CAMPO',
                'verbose_name_plural': 'TIPOS DE CAMPO',
                'db_table': 'TIPO_CAMPO',
            },
        ),
        migrations.CreateModel(
            name='SeccionFormulario',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_column='TITULO', max_length=40, verbose_name='Título')),
                ('formulario', models.ForeignKey(db_column='FORMULARIO_ID', on_delete=django.db.models.deletion.CASCADE, to='formulario.formulario', verbose_name='Formulario')),
            ],
            options={
                'verbose_name': 'SECCION DE FORMULARIO',
                'verbose_name_plural': 'SECCIONES DE FORMULARIO',
                'db_table': 'SECCION_FORMULARIO',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(db_column='ENUNCIADO', max_length=350, verbose_name='Enunciado de Pregunta')),
                ('campo', models.ForeignKey(db_column='TIPOC_ID', on_delete=django.db.models.deletion.CASCADE, to='formulario.tipocampo', verbose_name='Tipo de Campo')),
                ('formulario', models.ForeignKey(db_column='FORMULARIO_ID', on_delete=django.db.models.deletion.CASCADE, to='formulario.formulario', verbose_name='Formulario')),
                ('seccion', models.ForeignKey(db_column='SECCION_ID', on_delete=django.db.models.deletion.CASCADE, to='formulario.seccionformulario', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'PREGUNTA',
                'verbose_name_plural': 'PREGUNTAS',
                'db_table': 'PREGUNTA',
            },
        ),
    ]
