# Generated by Django 4.1.2 on 2022-10-18 19:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='TITULO', max_length=40)),
                ('descripcion', models.CharField(blank=True, db_column='DESCRIPCION', max_length=255)),
                ('creado', models.DateTimeField(db_column='FECHA_CREADO', default=datetime.datetime.now, editable=False)),
                ('plan', models.ForeignKey(db_column='PLAN_ID', on_delete=django.db.models.deletion.CASCADE, to='operacion.plan')),
            ],
            options={
                'verbose_name': 'FORMULARIO',
                'verbose_name_plural': 'FORMULARIOS',
                'db_table': 'FORMULARIO',
            },
        ),
        migrations.CreateModel(
            name='TipoCampo',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=20)),
            ],
            options={
                'verbose_name': 'TIPO DE CAMPO',
                'verbose_name_plural': 'TIPOS DE CAMPO',
                'db_table': 'TIPO_CAMPO',
            },
        ),
        migrations.CreateModel(
            name='SeccionFormulario',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='TITULO', max_length=40)),
                ('formulario', models.ForeignKey(db_column='FORMULARIO_ID', on_delete=django.db.models.deletion.CASCADE, to='formulario.formulario')),
            ],
            options={
                'verbose_name': 'SECCION DE FORMULARIO',
                'verbose_name_plural': 'SECCIONES DE FORMULARIO',
                'db_table': 'SECCION_FORMULARIO',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('enunciado', models.CharField(db_column='ENUNCIADO', max_length=350)),
                ('campo', models.ForeignKey(db_column='TIPOC_ID', on_delete=django.db.models.deletion.CASCADE, to='formulario.tipocampo')),
                ('formulario', models.ForeignKey(db_column='FORMULARIO_ID', on_delete=django.db.models.deletion.CASCADE, to='formulario.formulario')),
                ('seccion', models.ForeignKey(db_column='SECCION_ID', on_delete=django.db.models.deletion.CASCADE, to='formulario.seccionformulario')),
            ],
            options={
                'verbose_name': 'PREGUNTA',
                'verbose_name_plural': 'PREGUNTAS',
                'db_table': 'PREGUNTA',
            },
        ),
    ]
