# Generated by Django 4.1.2 on 2022-10-20 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_opcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='seccion',
            field=models.ForeignKey(blank=True, db_column='SECCION_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='formulario.seccionformulario', verbose_name='Sección'),
        ),
    ]
