# Generated by Django 4.1.2 on 2023-01-27 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EjeTrabajo',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=350, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Eje de trabajo',
                'verbose_name_plural': 'Ejes de trabajo',
                'db_table': 'EJE_TRABAJO',
            },
        ),
        migrations.CreateModel(
            name='PlanEje',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=350, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'db_table': 'PLAN_EJEPREVENCION',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=350, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'PRODUCTO',
            },
        ),
        migrations.CreateModel(
            name='Subproducto',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=350, verbose_name='Nombre')),
                ('producto', models.ForeignKey(db_column='PRODUCTO_ID', on_delete=django.db.models.deletion.CASCADE, to='eje_prevencion.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Subproducto',
                'verbose_name_plural': 'Subproductos',
                'db_table': 'SUBPRODUCTO',
            },
        ),
    ]
