# Generated by Django 4.1.2 on 2022-10-18 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=15)),
                ('url', models.CharField(db_column='URL', max_length=350)),
                ('icono', models.ImageField(db_column='ICONO', upload_to='social')),
            ],
            options={
                'verbose_name': 'RED SOCIAL',
                'verbose_name_plural': 'REDES SOCIALES',
                'db_table': 'RED_SOCIAL',
            },
        ),
        migrations.CreateModel(
            name='SeccionInicio',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='TITULO', max_length=50)),
                ('informacion', models.CharField(db_column='INFORMACION', max_length=350)),
            ],
            options={
                'verbose_name': 'SECCION INICIO',
                'verbose_name_plural': 'SECCIONES INICIO',
                'db_table': 'SECCION_INICIO',
            },
        ),
        migrations.CreateModel(
            name='ImgInicio',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('src', models.ImageField(db_column='SRC', null=True, upload_to='carrusel_seccion')),
                ('seccion', models.ForeignKey(db_column='SECCION_ID', on_delete=django.db.models.deletion.CASCADE, to='inicio.seccioninicio')),
            ],
            options={
                'verbose_name': 'IMAGEN INICIO',
                'verbose_name_plural': 'IMAGENES INCIO',
                'db_table': 'IMG_INICIO',
            },
        ),
    ]
