# Generated by Django 4.1.2 on 2022-10-27 11:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccioninicio',
            name='informacion',
            field=tinymce.models.HTMLField(db_column='INFORMACION', max_length=3000, verbose_name='Información'),
        ),
    ]
