# Generated by Django 4.1.2 on 2022-10-18 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=40)),
            ],
            options={
                'verbose_name': 'DEPARTAMENTO',
                'verbose_name_plural': 'DEPARTAMENTOS',
                'db_table': 'DEPARTAMENTO',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=40)),
                ('departamento', models.ForeignKey(db_column='DEPARTAMENTO_ID', on_delete=django.db.models.deletion.CASCADE, to='lugar.departamento')),
            ],
            options={
                'verbose_name': 'MUNICIPIOS',
                'verbose_name_plural': 'MUNICIPIOS',
                'db_table': 'MUNICIPIO',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('direccion', models.CharField(db_column='DIRECCION', max_length=150)),
                ('municipio', models.ForeignKey(db_column='MUNICIPIO_ID', on_delete=django.db.models.deletion.CASCADE, to='lugar.municipio')),
            ],
            options={
                'verbose_name': 'LUGAR',
                'verbose_name_plural': 'LUGARES',
                'db_table': 'LUGAR',
            },
        ),
    ]
