# Generated by Django 4.1.2 on 2022-10-18 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('motivo', models.CharField(db_column='MOTIVO', max_length=50)),
                ('mensaje', models.CharField(db_column='MENSAJE', max_length=350)),
                ('leido', models.BooleanField(db_column='LEIDO', default=False)),
                ('emisor', models.ForeignKey(db_column='EMISOR', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NOTIFICACION',
                'verbose_name_plural': 'NOTIFICACIONES',
                'db_table': 'NOTIFICACION',
            },
        ),
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('notificacion', models.ForeignKey(db_column='NOTIFICACION_ID', on_delete=django.db.models.deletion.CASCADE, to='notificacion.notificacion')),
                ('usuario', models.ForeignKey(db_column='USUARIO', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DESTINATARIO',
                'verbose_name_plural': 'DESTINATARIOS',
                'db_table': 'DESTINATARIO',
            },
        ),
    ]
