# Generated by Django 4.1.2 on 2022-11-10 23:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(db_column='MOTIVO', max_length=50, verbose_name='Motivo')),
                ('mensaje', models.CharField(blank=True, db_column='MENSAJE', max_length=350, verbose_name='Mensaje')),
                ('leido', models.BooleanField(db_column='LEIDO', default=False, verbose_name='Leído')),
                ('fechahora', models.DateTimeField(db_column='FECHA_HORA', default=datetime.datetime.now, editable=False, verbose_name='Feha y Hora')),
                ('receptor', models.ForeignKey(db_column='RECEPTOR', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Receptor')),
            ],
            options={
                'verbose_name': 'NOTIFICACION',
                'verbose_name_plural': 'NOTIFICACIONES',
                'db_table': 'NOTIFICACION',
            },
        ),
    ]
