# Generated by Django 4.1.2 on 2023-01-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanArea',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=350, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'db_table': 'PLAN_AREAOPERATIVA',
            },
        ),
        migrations.CreateModel(
            name='TipoOperativo',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=350, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de operativo',
                'verbose_name_plural': 'Tipos de operativo',
                'db_table': 'TIPO_OPERATIVO',
            },
        ),
    ]
