# Generated by Django 4.1.2 on 2023-01-22 08:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugar', '__first__'),
        ('eje_prevencion', '__first__'),
        ('delegacion', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaMensualEP',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.PositiveBigIntegerField(db_column='META_MES', verbose_name='Meta mensual')),
                ('meta_alcanzada', models.PositiveBigIntegerField(db_column='META_ALCANZADA', default=0, verbose_name='Meta alcanzada')),
                ('asignado', models.DateTimeField(db_column='FECHA_ASIGNADO', default=datetime.datetime.now, verbose_name='Fecha de creación')),
                ('estado', models.CharField(choices=[('na', 'No alcanzado'), ('a', 'Alcanzado'), ('s', 'Superado')], db_column='ESTADO', default='na', max_length=15, verbose_name='Estado')),
                ('actualizado', models.DateTimeField(db_column='FECHA_ACTUALIZADO', default=datetime.datetime.now, verbose_name='Fecha de actualización')),
                ('diferencia', models.BigIntegerField(blank=True, db_column='DIFERENCIA', verbose_name='Diferencia')),
                ('delegacion', models.ForeignKey(db_column='DELEGACION_ID', on_delete=django.db.models.deletion.CASCADE, to='delegacion.delegacion', verbose_name='Delegación')),
                ('eje', models.OneToOneField(db_column='eje', on_delete=django.db.models.deletion.CASCADE, to='eje_prevencion.ejetrabajo', verbose_name='Eje de Trabajo')),
            ],
            options={
                'verbose_name': 'Meta mensual eje de prevención',
                'verbose_name_plural': 'Metas mensuales eje de prevención',
                'db_table': 'META_MENSUAL_EJE_PREVENCION',
            },
        ),
        migrations.CreateModel(
            name='LugarPriorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_column='FECHA', default=datetime.datetime.now, editable=False, verbose_name='Fecha')),
                ('delegacion', models.ForeignKey(db_column='DELEGACION_ID', on_delete=django.db.models.deletion.CASCADE, to='delegacion.delegacion', verbose_name='Delegación')),
                ('lugar', models.ForeignKey(db_column='LUGAR_ID', on_delete=django.db.models.deletion.CASCADE, to='lugar.lugar', verbose_name='Lugar')),
            ],
            options={
                'verbose_name': 'Lugar Priorizado',
                'verbose_name_plural': 'Lugares Priorizados',
                'db_table': 'LUGAR_PRIORIZADO',
            },
        ),
    ]
