# Generated by Django 4.1.2 on 2022-11-10 23:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugar', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.PositiveBigIntegerField(db_column='META_MES', verbose_name='Meta mensual')),
                ('mes', models.CharField(choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], db_column='MES', max_length=15, verbose_name='Mes')),
                ('delegacion', models.OneToOneField(db_column='DELEGACION_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Delegación')),
            ],
            options={
                'verbose_name': 'META MENSUAL',
                'verbose_name_plural': 'META MENSUALES',
                'db_table': 'META_MENSUAL',
            },
        ),
        migrations.CreateModel(
            name='MetaDiariaAlcanzada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_alcanzada', models.PositiveBigIntegerField(db_column='META_ALCANZADA', verbose_name='Meta alcanzada')),
                ('fecha', models.DateTimeField(db_column='FECHA', default=datetime.datetime.now, verbose_name='Fecha')),
                ('alcanzada', models.BooleanField(db_column='ALCANZADA', default=False, verbose_name='Alcanzada')),
                ('superada', models.BooleanField(db_column='SUPERADA', default=False, verbose_name='Superada')),
                ('diferencia', models.BigIntegerField(db_column='DIFERENCIA', verbose_name='Diferencia')),
                ('meta_mensual', models.ForeignKey(db_column='META_MENSUAL', on_delete=django.db.models.deletion.CASCADE, to='asignacion.metamensual', verbose_name='Meta mensual')),
            ],
            options={
                'verbose_name': 'META DIARIA ALCANZADA',
                'verbose_name_plural': 'META DIARIA ALCANZADAS',
                'db_table': 'META_DIARIA_ALCANZADA',
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_column='FECHA', default=datetime.datetime.now, editable=False, verbose_name='Fecha')),
                ('delegacion', models.OneToOneField(db_column='DELEGACION_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Delegación')),
                ('lugar', models.OneToOneField(db_column='LUGAR_ID', on_delete=django.db.models.deletion.CASCADE, to='lugar.lugar', verbose_name='Lugar')),
            ],
            options={
                'verbose_name': 'ASIGNACION',
                'verbose_name_plural': 'ASIGNACIONES',
                'db_table': 'ASIGNACION',
            },
        ),
    ]
