# Generated by Django 4.1.2 on 2022-10-18 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='fecha',
            field=models.DateField(db_column='FECHA', default=datetime.datetime.now),
        ),
    ]
