# Generated by Django 4.1.2 on 2023-02-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metamensualep',
            name='diferencia_beneficiarios',
            field=models.BigIntegerField(blank=True, db_column='DIFERENCIA_BENEFICIARIOS', default=0, verbose_name='Diferencia Beneficiarios'),
        ),
        migrations.AddField(
            model_name='metamensualep',
            name='estado_beneficiarios',
            field=models.CharField(choices=[('na', 'No alcanzado'), ('a', 'Alcanzado'), ('s', 'Superado')], db_column='ESTADO_BENEFICIARIOS', default='na', max_length=15, verbose_name='Estado Beneficiarios'),
        ),
        migrations.AddField(
            model_name='metamensualep',
            name='meta_alcanzada_beneficicarios',
            field=models.PositiveBigIntegerField(db_column='META_ALCANZADA_BENEFICIARIOS', default=0, verbose_name='Meta alcanzada Beneficiarios'),
        ),
        migrations.AddField(
            model_name='metamensualep',
            name='meta_beneficiarios',
            field=models.PositiveBigIntegerField(db_column='META_MES_BENEFICIARIOS', default=0, verbose_name='Meta Mensual Beneficiarios'),
        ),
        migrations.AlterField(
            model_name='metamensualep',
            name='diferencia',
            field=models.BigIntegerField(blank=True, db_column='DIFERENCIA', default=0, verbose_name='Diferencia'),
        ),
    ]
