# Generated by Django 4.1.2 on 2022-10-18 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion', '0002_alter_asignacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='fecha',
            field=models.DateField(db_column='FECHA', default=datetime.datetime.now, editable=False),
        ),
    ]
